# Generated by Django 6.0.2 on 2026-09-03 06:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_department_loginattempt_organization_permission_and_more'),
        ('tenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('allowed_extensions', models.JSONField(default=list, help_text="e.g. ['.pdf', '.docx', '.jpg', '.png']")),
                ('max_file_size', models.BigIntegerField(default=26214400, help_text='Max file size in bytes (default 25MB)')),
                ('required', models.BooleanField(default=False)),
                ('requires_ocr', models.BooleanField(default=True)),
                ('requires_verification', models.BooleanField(default=False)),
                ('expiry_required', models.BooleanField(default=False)),
                ('versioning_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('TENDER', 'Tender'), ('VENDOR', 'Vendor'), ('BID', 'Bid'), ('EVALUATION', 'Evaluation'), ('AWARD', 'Award'), ('CONTRACT', 'Contract'), ('ORGANIZATION', 'Organization'), ('OTHER', 'Other')], db_index=True, default='TENDER', max_length=50)),
                ('owner_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(db_index=True, max_length=512)),
                ('storage_bucket', models.CharField(default='tenderx-documents', max_length=128)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('file_extension', models.CharField(default='.pdf', max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('sha256_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('encryption_status', models.CharField(default='SSE-KMS', max_length=50)),
                ('upload_status', models.CharField(choices=[('INITIATED', 'Initiated'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('FAILED', 'Failed')], default='INITIATED', max_length=30)),
                ('scan_status', models.CharField(choices=[('PENDING_SCAN', 'Pending Scan'), ('CLEAN', 'Clean / No Threats Detected'), ('INFECTED', 'Infected / Malicious'), ('QUARANTINED', 'Quarantined'), ('SCAN_FAILED', 'Scan Failed')], default='PENDING_SCAN', max_length=30)),
                ('ocr_status', models.CharField(choices=[('PENDING', 'Pending OCR'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVIEW_REQUIRED', 'Review Required (Low Confidence)'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=30)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('REVIEW_REQUIRED', 'Review Required')], default='UNVERIFIED', max_length=30)),
                ('lifecycle_status', models.CharField(choices=[('INITIATED', 'Initiated'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('SCANNING', 'Scanning'), ('OCR_PROCESSING', 'OCR Processing'), ('VERIFICATION', 'Pending Verification'), ('AVAILABLE', 'Available / Ready'), ('REJECTED', 'Rejected'), ('QUARANTINED', 'Quarantined'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], db_index=True, default='INITIATED', max_length=30)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('is_template', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_reason', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_documents', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('DOCUMENT_CREATED', 'Document Created'), ('DOCUMENT_VIEWED', 'Document Viewed'), ('DOCUMENT_DOWNLOADED', 'Document Downloaded'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_VERSION_CREATED', 'Document Version Created'), ('DOCUMENT_ARCHIVED', 'Document Archived'), ('DOCUMENT_RESTORED', 'Document Restored'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('DOCUMENT_ACCESSED', 'Document Accessed'), ('DOCUMENT_ACCESS_DENIED', 'Document Access Denied'), ('DOCUMENT_QUARANTINED', 'Document Quarantined'), ('DOCUMENT_OCR_PROCESSED', 'Document OCR Processed'), ('TEMPLATE_CREATED', 'Template Created'), ('TEMPLATE_VERSION_CREATED', 'Template Version Created'), ('DOCUMENT_GENERATED', 'Document Generated From Template')], max_length=50)),
                ('performed_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='documents.document')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentOCR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('extracted_text', models.TextField(blank=True)),
                ('language', models.CharField(default='en', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending OCR'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVIEW_REQUIRED', 'Review Required (Low Confidence)'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=30)),
                ('provider', models.CharField(choices=[('TESSERACT', 'Tesseract OCR'), ('TEXTRACT', 'AWS Textract'), ('MOCK', 'Enterprise Mock Provider')], default='MOCK', max_length=30)),
                ('processing_time', models.FloatField(default=0.0, help_text='Processing time in seconds')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_records', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('template_content', models.TextField(help_text='Template text with Mustache-style variables like {{tender.title}}')),
                ('variables_schema', models.JSONField(blank=True, default=dict, help_text='Schema describing expected variable definitions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates', to='tenders.tendercategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates', to='accounts.organization')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='documents.documenttype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=512)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('sha256_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('change_summary', models.TextField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('encryption_metadata', models.JSONField(blank=True, default=dict)),
                ('scan_status', models.CharField(choices=[('PENDING_SCAN', 'Pending Scan'), ('CLEAN', 'Clean / No Threats Detected'), ('INFECTED', 'Infected / Malicious'), ('QUARANTINED', 'Quarantined'), ('SCAN_FAILED', 'Scan Failed')], default='PENDING_SCAN', max_length=30)),
                ('ocr_status', models.CharField(choices=[('PENDING', 'Pending OCR'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVIEW_REQUIRED', 'Review Required (Low Confidence)'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=30)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('REVIEW_REQUIRED', 'Review Required')], default='UNVERIFIED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'lifecycle_status'], name='documents_d_organiz_70fe2d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner_type', 'owner_id'], name='documents_d_owner_t_855562_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'lifecycle_status'], name='documents_d_documen_6d0495_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expires_at', 'lifecycle_status'], name='documents_d_expires_bdb6c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
