# Generated by Django 4.2.30 on 2026-09-03 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenders', '0001_initial'),
        ('vendors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bid_reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMISSION_IN_PROGRESS', 'Submission In Progress'), ('SUBMITTED', 'Submitted'), ('AMENDMENT_ALLOWED', 'Amendment Allowed'), ('AMENDMENT_SUBMITTED', 'Amendment Submitted'), ('WITHDRAWAL_REQUESTED', 'Withdrawal Requested'), ('WITHDRAWN', 'Withdrawn'), ('LOCKED', 'Locked'), ('TECHNICAL_OPENED', 'Technical Opened'), ('TECHNICAL_EVALUATION', 'Technical Evaluation'), ('FINANCIAL_OPENING_AUTHORIZED', 'Financial Opening Authorized'), ('FINANCIAL_OPENED', 'Financial Opened'), ('EVALUATED', 'Evaluated'), ('AWARDED', 'Awarded'), ('REJECTED', 'Rejected'), ('DISQUALIFIED', 'Disqualified')], db_index=True, default='DRAFT', max_length=35)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bids', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tenders.tender')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidOpening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('TECHNICAL_AUTHORIZED', 'Technical Opening Authorized'), ('TECHNICAL_OPENED', 'Technical Opened'), ('FINANCIAL_AUTHORIZED', 'Financial Opening Authorized'), ('FINANCIAL_OPENED', 'Financial Opened'), ('COMPLETED', 'Opening Completed')], default='NOT_STARTED', max_length=30)),
                ('total_bids_received', models.PositiveIntegerField(default=0)),
                ('total_bids_locked', models.PositiveIntegerField(default=0)),
                ('integrity_checks_passed', models.PositiveIntegerField(default=0)),
                ('integrity_checks_failed', models.PositiveIntegerField(default=0)),
                ('technical_opening_authorized_at', models.DateTimeField(blank=True, null=True)),
                ('technical_opened_at', models.DateTimeField(blank=True, null=True)),
                ('technical_opening_notes', models.TextField(blank=True, null=True)),
                ('financial_opening_authorized_at', models.DateTimeField(blank=True, null=True)),
                ('financial_opened_at', models.DateTimeField(blank=True, null=True)),
                ('financial_opening_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_opening_authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_openings_authorized', to=settings.AUTH_USER_MODEL)),
                ('technical_opening_authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_openings_authorized', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_openings', to='tenders.tender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('methodology', models.TextField(blank=True, help_text='Technical approach and methodology', null=True)),
                ('technical_description', models.TextField(blank=True, help_text='Detailed technical description of the proposed solution', null=True)),
                ('implementation_plan', models.TextField(blank=True, help_text='Implementation timeline and approach', null=True)),
                ('delivery_plan', models.TextField(blank=True, help_text='Delivery schedule and milestones', null=True)),
                ('team_information', models.TextField(blank=True, help_text='Key personnel and their qualifications', null=True)),
                ('compliance_statement', models.TextField(blank=True, help_text='Statement of compliance with tender requirements', null=True)),
                ('equipment_details', models.TextField(blank=True, help_text='Equipment and resources to be deployed', null=True)),
                ('quality_assurance', models.TextField(blank=True, help_text='Quality assurance approach', null=True)),
                ('technical_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_bid', to='bids.bid')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Technical Bids',
            },
        ),
        migrations.CreateModel(
            name='FinancialBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('pricing_breakdown', models.JSONField(blank=True, default=dict)),
                ('encrypted_payload', models.TextField(blank=True, help_text='AES-256 encrypted financial payload for sealed bid protection', null=True)),
                ('encryption_key_ref', models.CharField(blank=True, help_text='Reference to encryption key in secret management system', max_length=255, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_bid', to='bids.bid')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_openings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Financial Bids',
            },
        ),
        migrations.CreateModel(
            name='BidWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Reason for withdrawal')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approval_remarks', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal', to='bids.bid')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bid Withdrawals',
            },
        ),
        migrations.CreateModel(
            name='BidIntegrityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integrity_hash', models.CharField(db_index=True, help_text='SHA-256 digest of canonical bid representation', max_length=128)),
                ('hash_components', models.JSONField(blank=True, default=dict, help_text='Record of what was included in the hash')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Integrity Verified'), ('FAILURE', 'Integrity Failure'), ('TAMPERED', 'Tampered')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('recomputed_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_record', to='bids.bid')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bid Integrity Records',
            },
        ),
        migrations.CreateModel(
            name='BidDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('TECHNICAL_PROPOSAL', 'Technical Proposal'), ('FINANCIAL_PROPOSAL', 'Financial Proposal'), ('COMPANY_REGISTRATION', 'Company Registration'), ('TAX_CERTIFICATE', 'Tax Certificate'), ('EXPERIENCE_CERTIFICATE', 'Experience Certificate'), ('WORK_ORDER', 'Work Order / Completion Certificate'), ('BANK_GUARANTEE', 'Bank Guarantee / Bid Security'), ('DECLARATION', 'Declaration / Affidavit'), ('AUTHORIZATION_LETTER', 'Authorization Letter'), ('OTHER', 'Other Supporting Document')], default='OTHER', max_length=40)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(blank=True, max_length=500, null=True)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('sha256_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SCANNING', 'Scanning'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UPLOADED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bids.bid')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bid_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BidAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=30, null=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(default='Bid', max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('DENIED', 'Denied')], default='SUCCESS', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_access_logs', to=settings.AUTH_USER_MODEL)),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='bids.bid')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BidVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('technical_snapshot', models.JSONField(blank=True, default=dict)),
                ('financial_snapshot', models.JSONField(blank=True, default=dict)),
                ('document_references', models.JSONField(blank=True, default=list)),
                ('change_summary', models.TextField(blank=True, null=True)),
                ('change_type', models.CharField(default='CREATED', max_length=50)),
                ('integrity_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='bids.bid')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('bid', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='BidOpeningAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_in_opening', models.CharField(choices=[('BID_OPENING_OFFICER', 'Bid Opening Officer'), ('AUTHORIZED_EVALUATOR', 'Authorized Evaluator'), ('TECHNICAL_EVALUATOR', 'Technical Evaluator'), ('FINANCIAL_EVALUATOR', 'Financial Evaluator'), ('AUDITOR', 'Auditor'), ('WITNESS', 'Witness')], max_length=50)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_opening_authorizations', to=settings.AUTH_USER_MODEL)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='bids.bidopening')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_opening_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('opening', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BidAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amendment_number', models.PositiveIntegerField()),
                ('reason', models.TextField(help_text='Reason for amendment')),
                ('changes_description', models.TextField(blank=True, help_text='Summary of changes made', null=True)),
                ('changed_sections', models.JSONField(blank=True, default=list, help_text='List of sections changed: ["technical", "financial", "documents"]')),
                ('previous_version', models.PositiveIntegerField()),
                ('new_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='bids.bid')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_amendments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['amendment_number'],
                'unique_together': {('bid', 'amendment_number')},
            },
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['tender', 'vendor'], name='bids_bid_tender__ec8a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['tender', 'status'], name='bids_bid_tender__446e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['vendor', 'status'], name='bids_bid_vendor__3945db_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['status', 'created_at'], name='bids_bid_status_19f72c_idx'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tender', 'vendor'), name='unique_active_bid_per_vendor_per_tender'),
        ),
    ]
